#ifndef _CONTROLS_H_
#define _CONTROLS_H_ 

#include <vpad/input.h>

#define TOUCH_SCREEN_CONTROLS_ENABLED 0

#define CONTROLS_ACCEPT VPAD_BUTTON_A
#define CONTROLS_CANCEL VPAD_BUTTON_B
#define CONTROLS_UP VPAD_BUTTON_UP
#define CONTROLS_DOWN VPAD_BUTTON_DOWN
#define CONTROLS_LEFT VPAD_BUTTON_LEFT
#define CONTROLS_RIGHT VPAD_BUTTON_RIGHT
#define CONTROLS_DIRECTION VPAD_BUTTON_B
#define CONTROLS_HORIZONTAL VPAD_BUTTON_Y
#define CONTROLS_VERTICAL VPAD_BUTTON_X
#define CONTROLS_BUILD_WALL (VPAD_BUTTON_A | VPAD_BUTTON_L | VPAD_BUTTON_R | VPAD_BUTTON_X | VPAD_BUTTON_Y)
#define CONTROLS_CONTINUE VPAD_BUTTON_A
#define CONTROLS_EXIT VPAD_BUTTON_PLUS

#define CONTROLS_KBENTER VPAD_BUTTON_PLUS

void updateControls();
u32 isKeyPressed(u32 key);
u32 isKeyDown(u32 key);
u32 isKeyReleased(u32 key);

#endif
